Nunit selenium
tallarium/openfin-tests pull request #1
Opened 2020-05-27 14:25 UTC by XuluWarrior

2020-05-27 21:03 UTC, mwhitworth requested changes
Perhaps worth linking to https://github.com/openfin/hello-openfin-selenium-example somewhere? (I presume this is where the code was adapted from)

I think the coverage is good for now though - given the main priority is to check basic runtime compatibility

2020-05-27 21:03 UTC, mwhitworth commented on openfin-csharp-api-test/openfin-csharp-api-test/OpenfinTests.cs
> +            fileServer = new HttpFileServer(dirToServe, 9070);
perhaps a comment as to why we need our own `HttpFileServer`?

2020-05-27 21:03 UTC, mwhitworth commented on openfin-csharp-api-test/openfin-csharp-api-test/Program.cs
> +﻿using Openfin.Desktop;
How is this file used?

2020-05-27 21:03 UTC, mwhitworth commented on openfin-csharp-api-test/openfin-csharp-api-test/OpenfinTests.cs
> +                fileServer.Stop();
`fileServer?.Stop()`

2020-05-27 21:03 UTC, mwhitworth commented on openfin-csharp-api-test/openfin-csharp-api-test/OpenfinTests.cs
> +                options.AddArgument("--remote-debugging-port=4444");
Factor out `4444` and `9070` as constants?

2020-05-27 21:03 UTC, mwhitworth commented on openfin-csharp-api-test/openfin-csharp-api-test/OpenfinTests.cs
> +            options.Version = "14.78.46.23";
factor out as constant?

2020-05-27 21:03 UTC, mwhitworth commented on openfin-csharp-api-test/openfin-csharp-api-test/OpenfinTests.cs
> +        public void Test()
Looks like something we can remove :)

2020-06-12 10:40 UTC, XuluWarrior commented on openfin-csharp-api-test/openfin-csharp-api-test/Program.cs
> +﻿using Openfin.Desktop;
I've removed the class methods.  But the tests only seem to run when project is a Console Application.  So the `Main` method is required.

2020-06-12 14:14 UTC, mwhitworth approved these changes

2020-06-12 14:14 UTC, mwhitworth commented on README.md
> +Currently each nunit needs to run independently to ensure they run successfully.
each nunit test?

2020-06-12 15:23 UTC, merged